extends Node

var tower_data = {
	"TowerKnight": {
		"damage": 30,
		"rof": 1.2,
		"range": 48,
		"cost": 5,
	},
	"TowerMage": {
		"damage": 10,
		"rof": 0.8,
		"range": 128,
		"cost": 3,
	} 
}

var enemies = [
	{
		"name": "EnemyButterfly",
		"base_damage": 1,
		"coin_amount": 1,
		"speed": 1.3,
		"hp": 50,
	},
	{
		"name": "EnemyBamboo",
		"base_damage": 1,
		"coin_amount": 1,
		"speed": 1,
		"hp": 70,
	},
	{
		"name": "EnemyLarva",
		"base_damage": 1,
		"coin_amount": 1,
		"speed": 0.5,
		"hp": 80,
	},
	{
		"name": "EnemyTanuki",
		"base_damage": 3,
		"coin_amount": 1,
		"speed": 1.1,
		"hp": 120,
	},
	{
		"name": "BossTanuki",
		"base_damage": 3,
		"coin_amount": 3,
		"speed": 0.5,
		"hp": 1500,
	},
]

var waves = {
	wave1 = [
		["EnemyLarva", 6],
		["EnemyLarva", 1],
		["EnemyLarva", 1],
		["EnemyLarva", 1],
		["EnemyLarva", 1],
		["EnemyLarva", 1],
		["EnemyLarva", 5],
		["EnemyBamboo", 3],
	],
	wave2 = [
		["EnemyBamboo", 1],
		["EnemyBamboo", 1],
		["EnemyBamboo", 1],
		["EnemyBamboo", 3],
		["EnemyLarva", 0.5],
		["EnemyLarva", 0.5],
		["EnemyBamboo", 0.5],
		["EnemyBamboo", 0.5],
		["EnemyLarva", 0.5],
		["EnemyBamboo", 0.5],
		["EnemyBamboo", 0.5],
		["EnemyButterfly", 0.5],
	],
	wave3 = [
		["EnemyButterfly", 1],
		["EnemyButterfly", 1],
		["EnemyLarva", 1],
		["EnemyButterfly", 3],
		["EnemyLarva", 0.5],
		["EnemyLarva", 0.5],
		["EnemyBamboo", 0.5],
		["EnemyButterfly", 0.5],
		["EnemyLarva", 0.5],
		["EnemyBamboo", 0.5],
		["EnemyBamboo", 0.5],
		["EnemyTanuki", 1],
	],
	wave4 = [
		["EnemyTanuki", 1],
		["EnemyTanuki", 1],
		["EnemyTanuki", 1],
		["EnemyTanuki", 3],
		["EnemyTanuki", 0.2],
		["EnemyTanuki", 0.2],
		["EnemyTanuki", 0.2],
		["EnemyTanuki", 0.2],
		["EnemyTanuki", 0.2],
		["EnemyTanuki", 0.2],
		["EnemyTanuki", 0.2],
		["EnemyTanuki", 0.2],
	],
	wave5 = [
		["EnemyButterfly", 1],
		["EnemyButterfly", 1],
		["EnemyButterfly", 1],
		["EnemyButterfly", 1],
		["EnemyButterfly", 1],
		["EnemyButterfly", 1],
		["EnemyButterfly", 1],
		["EnemyButterfly", 1],
		["EnemyTanuki", 0.5],
		["BossTanuki", 1],
		["EnemyTanuki", 1],
		["EnemyTanuki", 0.5],
		["EnemyTanuki", 1],
		["EnemyTanuki", 0.5],
	],
}
